# Generated by Django 3.0.6 on 2021-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pwd', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=70)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.IntegerField(default=700084)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
