# Generated by Django 3.0.6 on 2021-04-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'block',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('role', models.CharField(default='Admin', editable=False, max_length=100)),
                ('pwd', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pin', models.IntegerField(default=700084)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='village',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=100)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.block')),
            ],
            options={
                'db_table': 'village',
            },
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.country')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='funding_agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faname', models.CharField(max_length=100)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
            ],
            options={
                'db_table': 'funding_agency',
            },
        ),
        migrations.CreateModel(
            name='districts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.states')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.districts'),
        ),
    ]
